on:
  push:
    branches:
      - main
      - actions

name: "Build & Release"
jobs:
  generate:
    name: Generate codes
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18'

      - name: Installing all dependencies
        working-directory: server
        run: go get ./...

#      - uses: actions/setup-java@v2
#        with:
#          distribution: 'zulu'
#          java-version: '11'
#
#      - name: Push to Releases
#        uses: ncipollo/release-action@v1
#        with:
#          artifacts: "${{ matrix.dir }}/build/app/outputs/apk/debug/*"
#          tag: v1.0.${{ github.run_number }}
#          token: ${{ secrets.GITHUB_TOKEN }}
