on:
  push:
    branches:
      - main
      - actions

name: "Build & Release"
jobs:
  generate:
    name: Generate codes
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18'

      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Installing go server dependencies
        working-directory: server
        run: |
          export PATH=$PATH:$GOROOT/bin:$GOPATH/bin
          go install

      - name: setup-android-tools
        uses: maxim-lobanov/setup-android-tools@v1
        with:
          packages: ndk;19.2.5345600

      - name: Build aar
        working-directory: server
        run: |
          go install golang.org/x/mobile/cmd/gomobile@latest
          go install golang.org/x/mobile/cmd/gobind@latest
          go get golang.org/x/mobile/cmd/gobind
          go get golang.org/x/mobile/cmd/gomobile
          gomobile init
          gomobile bind -v -o ../client/app/libs/server.aar -target=android ./lib
        env:
          GOPROXY: https://proxy.golang.org,direct
          GO111MODULE: "on"

      - name: Push aar to release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "client/app/libs/*.aar"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.GITHUB_TOKEN }}

