on:
  push:
    branches:
      - main
      - actions

name: "Build & Release"
jobs:
  generate:
    name: Generate codes
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18'

      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Installing go server dependencies
        working-directory: server
        run: |
          export PATH=$PATH:$GOROOT/bin:$GOPATH/bin
          go install

      - name: setup-android-tools
        uses: maxim-lobanov/setup-android-tools@v1
        with:
          packages: ndk;19.2.5345600

      - name: Building app
        shell: pwsh
        run: ./scripts/build_app.ps1
        env:
          GOPROXY: https://proxy.golang.org,direct
          GO111MODULE: "on"

      - name: Push aar and apk to release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "client/app/libs/*.aar,client/app/build/outputs/apk/release/*.apk"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.GITHUB_TOKEN }}

