on:
  push:
    branches:
      - main
      - actions

name: "Build & Release"
jobs:
  generate:
    name: Generate codes
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Installing go server dependencies
        working-directory: server
        run: go install

      - name: setting go path
        run: export PATH=$PATH:$HOME/go/bin

      - uses: nttld/setup-ndk@v1
        id: ndk
        with:
            ndk-version: '19.2.5345600'
            add-to-path: true

      - name: Build aar
        working-directory: server
        run: |
          go get -d golang.org/x/mobile/cmd/gomobile
          export PATH=$PATH:$GOPATH/bin
          gomobile init
          gomobile bind -v -o ../client/app/libs/server.aar -target=android ./lib
        env:
          ANDROID_NDK_HOME: ${{ steps.ndk.outputs.ndk-path }}

      - name: Push aar to release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ matrix.dir }}/client/app/libs/*aar"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.GITHUB_TOKEN }}

